// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReverseProxy.Store.EFCore;

#nullable disable

namespace ReverseProxy.Store.EFCore.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    partial class EFCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReverseProxy.Store.Entities.RouteQueryParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ProxyMatchId")
                        .HasColumnType("int");

                    b.Property<string>("Values")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProxyMatchId");

                    b.ToTable("RouteQueryParameter");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entities.SessionAffinityCookie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<string>("Expiration")
                        .HasColumnType("longtext");

                    b.Property<bool?>("HttpOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsEssential")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaxAge")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<int?>("SameSite")
                        .HasColumnType("int");

                    b.Property<int?>("SecurePolicy")
                        .HasColumnType("int");

                    b.Property<int>("SessionAffinityConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionAffinityConfigId")
                        .IsUnique();

                    b.ToTable("SessionAffinityCookie");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entities.WebProxyConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<bool?>("BypassOnLocal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HttpClientConfigId")
                        .HasColumnType("int");

                    b.Property<bool?>("UseDefaultCredentials")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("HttpClientConfigId")
                        .IsUnique();

                    b.ToTable("WebProxyConfig");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ActiveHealthCheckOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HealthCheckOptionsId")
                        .HasColumnType("int");

                    b.Property<string>("Interval")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<string>("Policy")
                        .HasColumnType("longtext");

                    b.Property<string>("Timeout")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckOptionsId")
                        .IsUnique();

                    b.ToTable("ActiveHealthCheckOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Cluster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoadBalancingPolicy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("ClusterId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Health")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ForwarderRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActivityTimeout")
                        .HasColumnType("longtext");

                    b.Property<bool?>("AllowResponseBuffering")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClusterId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Version")
                        .HasColumnType("longtext");

                    b.Property<string>("VersionPolicy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("RequestProxyOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.HealthCheckOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvailableDestinationsPolicy")
                        .HasColumnType("longtext");

                    b.Property<string>("ClusterId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("HealthCheckOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.HttpClientConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClusterId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("DangerousAcceptAnyServerCertificate")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("EnableMultipleHttp2Connections")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxConnectionsPerServer")
                        .HasColumnType("int");

                    b.Property<string>("RequestHeaderEncoding")
                        .HasColumnType("longtext");

                    b.Property<string>("SslProtocols")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("ProxyHttpClientOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Metadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClusterId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProxyRouteId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("ProxyRouteId");

                    b.ToTable("Metadatas");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.PassiveHealthCheckOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("HealthCheckOptionsId")
                        .HasColumnType("int");

                    b.Property<string>("Policy")
                        .HasColumnType("longtext");

                    b.Property<string>("ReactivationPeriod")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("HealthCheckOptionsId")
                        .IsUnique();

                    b.ToTable("PassiveHealthCheckOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ProxyMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Hosts")
                        .HasColumnType("longtext");

                    b.Property<string>("Methods")
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.Property<int>("ProxyRouteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProxyRouteId")
                        .IsUnique();

                    b.ToTable("ProxyMatches");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ProxyRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthorizationPolicy")
                        .HasColumnType("longtext");

                    b.Property<string>("ClusterId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CorsPolicy")
                        .HasColumnType("longtext");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<string>("RouteId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.ToTable("ProxyRoutes");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.RouteHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("ProxyMatchId")
                        .HasColumnType("int");

                    b.Property<string>("Values")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProxyMatchId");

                    b.ToTable("RouteHeaders");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.SessionAffinityConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AffinityKeyName")
                        .HasColumnType("longtext");

                    b.Property<string>("ClusterId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FailurePolicy")
                        .HasColumnType("longtext");

                    b.Property<string>("Policy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("SessionAffinityOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.SessionAffinityOptionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SessionAffinityOptionSettings");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Transform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProxyRouteId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProxyRouteId");

                    b.ToTable("Transforms");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entities.RouteQueryParameter", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.ProxyMatch", "ProxyMatch")
                        .WithMany("QueryParameters")
                        .HasForeignKey("ProxyMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxyMatch");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entities.SessionAffinityCookie", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.SessionAffinityConfig", "SessionAffinityConfig")
                        .WithOne("Cookie")
                        .HasForeignKey("ReverseProxy.Store.Entities.SessionAffinityCookie", "SessionAffinityConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionAffinityConfig");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entities.WebProxyConfig", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.HttpClientConfig", "HttpClientConfig")
                        .WithOne("WebProxy")
                        .HasForeignKey("ReverseProxy.Store.Entities.WebProxyConfig", "HttpClientConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HttpClientConfig");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ActiveHealthCheckOptions", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.HealthCheckOptions", "HealthCheckOptions")
                        .WithOne("Active")
                        .HasForeignKey("ReverseProxy.Store.Entity.ActiveHealthCheckOptions", "HealthCheckOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCheckOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Destination", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.Cluster", "Cluster")
                        .WithMany("Destinations")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ForwarderRequest", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.Cluster", "Cluster")
                        .WithOne("HttpRequest")
                        .HasForeignKey("ReverseProxy.Store.Entity.ForwarderRequest", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.HealthCheckOptions", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.Cluster", "Cluster")
                        .WithOne("HealthCheck")
                        .HasForeignKey("ReverseProxy.Store.Entity.HealthCheckOptions", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.HttpClientConfig", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.Cluster", "Cluster")
                        .WithOne("HttpClient")
                        .HasForeignKey("ReverseProxy.Store.Entity.HttpClientConfig", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Metadata", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.Cluster", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ReverseProxy.Store.Entity.Destination", null)
                        .WithMany("Metadata")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ReverseProxy.Store.Entity.ProxyRoute", null)
                        .WithMany("Metadata")
                        .HasForeignKey("ProxyRouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.PassiveHealthCheckOptions", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.HealthCheckOptions", "HealthCheckOptions")
                        .WithOne("Passive")
                        .HasForeignKey("ReverseProxy.Store.Entity.PassiveHealthCheckOptions", "HealthCheckOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthCheckOptions");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ProxyMatch", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.ProxyRoute", "ProxyRoute")
                        .WithOne("Match")
                        .HasForeignKey("ReverseProxy.Store.Entity.ProxyMatch", "ProxyRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxyRoute");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ProxyRoute", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.Cluster", "Cluster")
                        .WithMany("ProxyRoutes")
                        .HasForeignKey("ClusterId");

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.RouteHeader", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.ProxyMatch", "ProxyMatch")
                        .WithMany("Headers")
                        .HasForeignKey("ProxyMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProxyMatch");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.SessionAffinityConfig", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.Cluster", "Cluster")
                        .WithOne("SessionAffinity")
                        .HasForeignKey("ReverseProxy.Store.Entity.SessionAffinityConfig", "ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Transform", b =>
                {
                    b.HasOne("ReverseProxy.Store.Entity.ProxyRoute", null)
                        .WithMany("Transforms")
                        .HasForeignKey("ProxyRouteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Cluster", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("HealthCheck");

                    b.Navigation("HttpClient");

                    b.Navigation("HttpRequest");

                    b.Navigation("Metadata");

                    b.Navigation("ProxyRoutes");

                    b.Navigation("SessionAffinity");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.Destination", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.HealthCheckOptions", b =>
                {
                    b.Navigation("Active");

                    b.Navigation("Passive");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.HttpClientConfig", b =>
                {
                    b.Navigation("WebProxy");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ProxyMatch", b =>
                {
                    b.Navigation("Headers");

                    b.Navigation("QueryParameters");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.ProxyRoute", b =>
                {
                    b.Navigation("Match");

                    b.Navigation("Metadata");

                    b.Navigation("Transforms");
                });

            modelBuilder.Entity("ReverseProxy.Store.Entity.SessionAffinityConfig", b =>
                {
                    b.Navigation("Cookie");
                });
#pragma warning restore 612, 618
        }
    }
}
